#!/bin/sh
#DEBHELPER#
set -e

if [ "$1" = "remove" ]; then
    rm -rf /var/log/neuca/*
    rm -rf /var/lib/neuca/storage/*
    for i in /var/lib/neuca/*; do
        if [ ! -d $i ]; then
            rm -f $i
        fi
    done
fi
